version: 2
jobs:
  build:
    docker:
      - image: nokamoto13/geckodriver-scala:0.0.0
    steps:
      - restore_cache:
          key: sbt-cache-v2
      - run:
          command: apt-get install -y git
      - checkout
      - run:
          name: Checkout submodule
          command: |
            git submodule init
            git submodule update --remote
      - run:
          command: sbt scalafmt::test test:scalafmt::test sbt:scalafmt::test
      - run:
          command: xvfb-run sbt test
      - save_cache:
          key: sbt-cache-v2
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
